### ISSUE TITLE
What is the LICENSE?

### ISSUE THREAD

**Issue by ashim-k-saha** [siriwatknp/mui-treasury#1]

**Comment by siriwatknp** [comment]
My intention is to make it free for every developers who love Material-UI. I don't have knowledge about license, may be the same as official Material-UI. Suggestion?

**Comment by davidedantonio** [comment]
Let’s take a look at this https://www.linux.it/scegli-una-licenza/licenses/mit/

**Comment by siriwatknp** [comment]
@davidedantonio Thanks a lot. Yeah, MIT license sounds good.
