### ISSUE TITLE
Layout Not working with Material UI 5

### ISSUE THREAD

**Issue by ilterugur** [siriwatknp/mui-treasury#1047]
Hello. Thank you so much for creating this mui ecosystem.

I'm using the last version of MUI-Treasury/layout. It was working great on Material-UI 4 but when I updated Material-UI to v5, I realised that MUI-Treasury/layout is not compatible with it. Are there any planned updates about it?

**Comment by siriwatknp** [comment]
I am waiting material-ui v5 to be stable and then I will upgrade the library. currently, I am not sure how much changes in v5.

**Comment by siriwatknp** [comment]
Please try again. https://www.npmjs.com/package/@mui-treasury/layout/v/5.0.0
