### ISSUE TITLE
[Layout] Support Material-UI V5

### ISSUE THREAD

**Issue by siriwatknp** [siriwatknp/mui-treasury#1070]
Material-UI v5 is at the finishing line. Once the migration is done, should fix
- #971 
- #1047
- #926

**Comment by mirshahnewaz** [comment]
Hi there,
After migrating Material UI from V4 to V5, I am getting the following error on Mui Treasury
Module not found: Can't resolve '@material-ui/core/styles/makeStyles' in '.....\node_modules\@mui-treasury\styles\info\apex'

Could you advise a solution?

thanks

**Comment by siriwatknp** [comment]
For layout v5, the work in progress is here.
https://siriwatknp.github.io/mui-treasury/?path=/story/layout-introduction--page

**Comment by mirshahnewaz** [comment]
Thanks for your response. However, I have a slightly different issue.
I was using your Social (Who to follow) thing. But After migrating to V5 it stopped working. It gives me the following error: 
Module not found: Can't resolve '@material-ui/core/styles/makeStyles' in '.....\node_modules@mui-treasury\styles\info\apex'

Do you have any solution for me pls? Is there a work-around I can use to fix this?
 
![image](https://user-images.githubusercontent.com/41802891/122190066-637e6000-ce89-11eb-92e4-af9d537acc95.png)

**Comment by siriwatknp** [comment]
@mirshahnewaz I will try to make it works this weekend.

**Comment by mirshahnewaz** [comment]
Wow, that would be perfect 👍 .
Look forward to it @siriwatknp

**Comment by siriwatknp** [comment]
@mirshahnewaz Please try the steps in [README](https://github.com/siriwatknp/mui-treasury/blob/master/README.md#mui-treasurycomponents-mui-treasurystyles)

**Comment by mirshahnewaz** [comment]
@siriwatknp very much appreciated - great work 👍 .
one last question - any idea when this package will improved so that we won't have to sets of style engines to keep the bundle size to a minimum? any rough date? Is it weeks, months?
Thanks again!

**Comment by siriwatknp** [comment]
@aress31 Is this [example](https://next.mui-treasury.com/?path=/story/layout-feature-multiple-headers--page) suffice?

> Note: You made a typo for `Subheader`, you forgot to capitalise it properly `SubHeader`.

I am not sure about this but I found `Subheader` in google and material-ui also has `ListSubheader` component.

**Comment by aress31** [comment]
@siriwatknp this example is fine, thanks!

**Comment by aress31** [comment]
What is the status of the upgrade to `V5`? So far, using the following dependencies:

```js
"dependencies": {
    "@emotion/react": "^11.4.1",
    "@emotion/styled": "^11.3.0",
    "@hookform/resolvers": "^2.8.0",
    "@mui-treasury/layout": "^5.0.0-alpha.20",
    "@mui/icons-material": "^5.0.0-rc.1",
    "@mui/material": "^5.0.0-rc.1",
    --- REDACTED ---
}
```

I am getting this error:

```
Failed to compile.

./node_modules/@mui-treasury/layout/esm/Header/Header.js
Module not found: Can't resolve '@material-ui/core/AppBar' in 'C:\Users\ateyar\GitHub\aegiscyber\aegiscyber-ng\node_modules\@mui-treasury\layout\esm\Header'
```

Could you please advise on the above? 🙏

**Comment by siriwatknp** [comment]
@aress31 will fix it today.

**Comment by siriwatknp** [comment]
@aress31 fixed in `@mui-treasury/layout@5.0.0-alpha.21`

**Comment by aress31** [comment]
@siriwatknp thanks for being so reactive, however, after upgrading to latest version I now get:

```
Failed to compile.

./src/App.js
Attempted import error: 'Content' is not exported from '@mui-treasury/layout'.
```

This is my import in `App.js`:

```js
import {
  Content,
  EdgeSidebar,
  Footer,
  Header,
  Root,
  SidebarContent,
} from '@mui-treasury/layout';
```

**Comment by aress31** [comment]
Thanks for being so reactive @siriwatknp !

**Comment by maurosbu** [comment]
@siriwatknp many thanks for this great library.

![MUITreasuryLayoutV5](https://user-images.githubusercontent.com/1393996/138282262-f8e1b218-8408-4433-82f9-f9d25ec1e7a9.png)

I'm using v5 (alpha 21) and I have a couple of questions.

1. In dark mode there isn't any difference between header and content (no divider), is it intentional (or a bug)?
2. Color of selected / disabled menu entries in sidebar depends on primary color (in V4 was grayscale based), is it intentional (or a bug)?
3. Switch from CollapsedBtn to EdgeTrigger in a List based menu is not straightforward, this is the code I used in order to force it to looks like a ListItem. The problem is that it is transparent. 



        <AppSidebar collapsed={leftEdgeSidebar?.collapsed} />
        <Divider />
        <EdgeTrigger
          component={List}
          target={{ anchor: "left", field: "collapsed" }}
        >
          {(collapsed, setCollapsed) => (
            <>
              <ListItem
                button
                onClick={() => setCollapsed(!collapsed)}
                sx={{ justifyContent: "center" }}
              >
                {collapsed ? <ArrowForwardIcon /> : <ArrowBackIcon />}
              </ListItem>
            </>
          )}
        </EdgeTrigger>


Many thanks for your help.

Mauro

**Comment by jordiyapz** [comment]
Hi, how are the progresses on this support?

**Comment by siriwatknp** [comment]
@jordiyapz It is done. https://www.npmjs.com/package/@mui-treasury/layout/v/5.0.0
