### ISSUE TITLE
Key Order Impact Render

### ISSUE THREAD

**Issue by aress31** [siriwatknp/mui-treasury#1156]
Oddly enough, the order of definition of the layout property affect the render, I had to specifically disable my `eslint rule` otherwise at the `sm` breakpoint my `width` will not be honoured:

```js
  leftEdgeSidebar: {
    config: {
      xs: {
        variant: 'temporary',
        width: 256,
      },
      // eslint-disable-next-line
      sm: {
        collapsible: false,
        persistentBehavior: 'fit',
        variant: 'persistent',
        width: 256,
      },
    },
    hidden: ['md', 'lg', 'xl'],
  },
```

Could you please look into that when you have some free time?

Thanks,
aress31

**Comment by siriwatknp** [comment]
Sorry, I don't understand this issue. Can you explain more and maybe a sandbox that I can reproduced?

**Comment by aress31** [comment]
The json object must be sorted as follow `xs, sm, md` otherwise it is not working. You can try `md, sm, xs` and you will see.

**Comment by siriwatknp** [comment]
> The json object must be sorted as follow `xs, sm, md` otherwise it is not working. You can try `md, sm, xs` and you will see.

Ah, I got your point now. will look into that soon.

**Comment by aress31** [comment]
@siriwatknp any update on this ticket?

**Comment by siriwatknp** [comment]
@aress31 For this case, I think it is better to add a document to indicate that the order matters. If the layout supports any order, it means more calculation which I don't think it is worth at this point because the config is one-time setup. Does this makes sense to you?

**Comment by aress31** [comment]
Yes it does, you are right documenting this is important.
