### ISSUE TITLE
can't import CardMediaStyle 

### ISSUE THREAD

**Issue by conghbnb** [siriwatknp/mui-treasury#1160]
although i install @mui-treasury/styles, but i can't import
![image](https://user-images.githubusercontent.com/62021923/134765961-7e026a3c-158a-4582-829f-7f9fe440922b.png)

**Comment by conghbnb** [comment]
@siriwatknp help me, pls

**Comment by siriwatknp** [comment]
As a workaround, you can copy the code from this repo manually.

For example, `useCoverCardMediaStyles` => https://github.com/siriwatknp/mui-treasury/blob/master/packages/mui-styles/src/cardMedia/cover/coverCardMedia.styles.js
