### ISSUE TITLE
Cannot read properties of undefined (reading 'type')

### ISSUE THREAD

**Issue by VityaSchel** [siriwatknp/mui-treasury#1162]
```
tabsStyles
node_modules/@mui-treasury/styles/esm/tabs/apple/appleTabs.styles.js:9
   6 |     breakpoints = _ref.breakpoints;
   7 | return createStyles({
   8 |   root: {
>  9 |     backgroundColor: palette.type === 'light' ? '#eee' : palette.divider,
  10 |     borderRadius: 10,       ^
  11 |     minHeight: 44
  12 |   },
```

```jsx
function Switch(props) {
  const tabsStyles = appleTabsStylesHook.useTabs()
  const tabItemStyles = appleTabsStylesHook.useTabItem()

  return (
    <Tabs
      classes={tabsStyles}
      // ...
    >
      <Tab classes={tabItemStyles} disableRipple label='Test' />
    </Tabs>
  )
}
```

React 17
@mui-treasury/styles@1.13.1
macOS 11.4

**Comment by VityaSchel** [comment]
I'm not using styles btw, I tried using ThemeProvider + createTheme but then it crash with same error

**Comment by shirinapr** [comment]
> les btw, I tried using ThemeProvider + createTheme but then it crash with same error

hey could you find a way to fix this?

**Comment by Lautaroef** [comment]
same error...

**Comment by VityaSchel** [comment]
> > les btw, I tried using ThemeProvider + createTheme but then it crash with same error
> 
> hey could you find a way to fix this?

Yes, I used patch-package and then bundled my project with webpack, seems to work in production :suspect:

**Comment by Sitaras** [comment]
same error...
any solution ?

**Comment by VityaSchel** [comment]
> same error...
> any solution ?
> 
> 

use patch package as I mentioned earlier

**Comment by siriwatknp** [comment]
I think it should be `palette.mode` in Material UI v5. This should work with the latest block https://mui-treasury.com/?path=/story/tabs-apple--apple
