### ISSUE TITLE
Official Release MUI5

### ISSUE THREAD

**Issue by aress31** [siriwatknp/mui-treasury#1166]
This is just a question about the release date for the non-beta/optimised version of `@mui-treasury/layout` (so far still in `1.0.1-alpha.4`). Most of the third-party MUI libraries have already been updated to support the latest version. Also, will the doc be updated too?

**Comment by aress31** [comment]
Amazing, thanks @siriwatknp bundle size is particularly important, hope this final release will be light weight. 😅

**Comment by ShotSkydiver** [comment]
@siriwatknp are there any plans to update the components and style packages? I use the ParallaxSlide and DotIndicator from components, i've currently got a fork with mui v5 updates but it'd be nice if it was fully updated to move away from the old mui styles!

**Comment by Yanians** [comment]
Is documentation is ready for this ?
