### ISSUE TITLE
Fixed Side Nav Position when header Clipped

### ISSUE THREAD

**Issue by KushalKatta** [siriwatknp/mui-treasury#117]
**Description**
When the header is fixed, clipped, and the side drawer is permanent or persistent then side nav first item is not visible because it is behind the header app bar

I have tried all presets and custom made using Layout Builder but couldn't resolve the issue.

**To Reproduce**
1. In a set environment with all required files, use 
`<Root config={presets.createMuiTreasuryLayout()} >`
2. try adding data in `<Header>` and `<Nav>`
3. Now In Computer Browser, with full resolution(>960px), you may notice header is clipped and side nav's first (or first few items depending on height) are not visible.

**Expected behavior**
It would be better if there was top margin when drawer is permanent or persistent and  header is clipped

**Screenshots**
<img width="713" alt="Screenshot 2019-08-16 at 5 49 26 PM" src="https://user-images.githubusercontent.com/12483126/63167253-5d7d8500-c04e-11e9-88c9-ec30cc1e504b.png">

<img width="1000" alt="Screenshot 2019-08-16 at 5 49 45 PM" src="https://user-images.githubusercontent.com/12483126/63167263-62423900-c04e-11e9-8ea0-5bd669600f3b.png">
Notice in above image that Inbox(First Item) is hidden because App Header Bar is overlapping it.

**Comment by siriwatknp** [comment]
@KushalKatta Thanks, I will look into it asap.

**Comment by siriwatknp** [comment]
by the way @KushalKatta what version of `mui-layout` that you use

**Comment by Niceight** [comment]
I have same problem and I use mui-layout from the layout builder

**Comment by Niceight** [comment]
> I have same problem and I use mui-layout from the layout builder

https://siriwatknp.github.io/mui-layout/?path=/story/examples--height-100vh
maybe this might the problem

**Comment by KushalKatta** [comment]
> by the way @KushalKatta what version of `mui-layout` that you use

I am not sure, maybe Layout-v1.1 😐

**Comment by siriwatknp** [comment]
Hello. can you try this version (it is 2.0 now)
https://codesandbox.io/s/material-ui-layout-v200-beta-7mn9xq3nnj
or here
https://mui-treasury.com/layout/demo

**Comment by siriwatknp** [comment]
@KushalKatta Sorry for the delay. By default, if the Header is fixed & clipped. there will be a `dummy` div that exist inside nav. please check that you **don't** set `heightAdjustmentDisabled` to true.
![image](https://user-images.githubusercontent.com/18292247/69010747-3f009000-0995-11ea-8769-884870a1e950.png)
