### ISSUE TITLE
Drawer Custom Elevation

### ISSUE THREAD

**Issue by aress31** [siriwatknp/mui-treasury#1176]
I am trying to reduce the default Drawer elevation for my dark mode as follows:
```js
 <SidebarContent PaperProps={{ elevation: 10 }}>
  --- SNIP ---
 </SidebarContent>
```

It seems however that the options are not being forwarded to the `Paper` component.

Would you mind have a look at this?

**Comment by siriwatknp** [comment]
The `SidebarContent` does not inherit the `Paper`. Can you try the `sx` prop?

```js
<SidebarContent sx={{ boxShadow: theme => theme.shadows[4] }}>
...
</SidebarContent>
```

**Comment by siriwatknp** [comment]
Check out the [new site](https://mui-treasury.com). Now you own the source code, adjust as you need!
