### ISSUE TITLE
Can't install @mui-treasury/components

### ISSUE THREAD

**Issue by rbit-123** [siriwatknp/mui-treasury#1183]
npm ERR! code ERESOLVE
npm ERR! ERESOLVE unable to resolve dependency tree
npm ERR!
npm ERR! While resolving: frontend@0.1.0
npm ERR! Found: @material-ui/core@5.0.0-beta.5
npm ERR! node_modules/@material-ui/core
npm ERR!   @material-ui/core@"^5.0.0-beta.5" from the root project
npm ERR!
npm ERR! Could not resolve dependency:
npm ERR! peer @material-ui/core@"^4.x" from @mui-treasury/components@1.10.1
npm ERR! node_modules/@mui-treasury/components
npm ERR!   @mui-treasury/components@"*" from the root project
npm ERR!
npm ERR! Fix the upstream dependency conflict, or retry
npm ERR! this command with --force, or --legacy-peer-deps
npm ERR! to accept an incorrect (and potentially broken) dependency resolution.
npm ERR!
npm ERR! See C:\Users\tanshul\AppData\Local\npm-cache\eresolve-report.txt for a full report.

npm ERR! A complete log of this run can be found in:

**Comment by siriwatknp** [comment]
We are moving away from npm packages, please check the new instruction https://mui-treasury.com/
