### ISSUE TITLE
Repo for GMail clone?

### ISSUE THREAD

**Issue by daskabe** [siriwatknp/mui-treasury#1186]
Hi, is there a stand alone repo that has one of the clones by themselves? The clones are great starting point to play around with layout ideas etc.

I created new react app from scratch and imported the gmail clone demo file _GmailDemo.js_ to my Layout folder and then started importing components and build libraries by looking at the website folder in this repo. I have not gotten it to work yet. I thought I should ask before I spend more time on getting this to work in standalone app.
Thanks.

**Comment by siriwatknp** [comment]
I recommend looking at Layout v6 Gmail as a starting point https://mui-treasury.com/?path=/story/layout-v6-app-gmail--gmail
