### ISSUE TITLE
Left sidebar collapse affecting main content element behavior

### ISSUE THREAD

**Issue by martinsvb** [siriwatknp/mui-treasury#1192]
I encounter strange issue with collapsed left sidebar.
We have MUI content structure like this: <TreasuryContent /><MuiContainer /><RouterOutlet /><MuiBox /><MuiTabs />
Tabs are initialized with empty "New item" tab.
We can add other new items by plus button on the right or existing from left menu.
Problem is, when sidebar is collapsed first new item tab has simple cursor and it's not clickable for change.
There is pointer only on small top and bottom space.
If I expand
![Sidebar_co
![Sidebar_expanded](https://user-images.githubusercontent.com/6408519/177082680-9a3c2da3-7ad1-479d-ae74-670db6ba2042.png)
llapsed](https://user-images.githubusercontent.com/6408519/177082671-ac00a939-0c6d-403d-b8c3-5219ba972ae6.png)
 Sidebar tab is working normally with cursor pointer.
There is only changing class on main element generated by Treasury Content.
I don't have idea, what is causing this issue.
Maybe it's on our side.
I don't know.
I can try reproduce it in js fiddle.
Thank you for good library!

**Comment by martinsvb** [comment]
![Sidebar_expanded](https://user-images.githubusercontent.com/6408519/177082743-6c53dd0c-6e80-407a-92a9-2f29d3027aa0.png)

**Comment by martinsvb** [comment]
Content structure:
`<TreasuryContent /><MuiContainer /><RouterOutlet /><MuiBox /><MuiTabs />`

**Comment by siriwatknp** [comment]
Not sure what's the issue. Need a reproducible sandbox.
