### ISSUE TITLE
Help with layout configuration: header clipped with temporay sidebar

### ISSUE THREAD

**Issue by gremo** [siriwatknp/mui-treasury#1208]
As you can see from my scheme, the `header` is clipped (above sidebar) starting from `lg` breakpoint:

```tsx
import { Scheme } from '@mui-treasury/layout';

export const layout: Scheme = {
  header: {
    config: {
      xs: { position: 'fixed', height: 56, clipped: false },
      lg: { position: 'fixed', height: 64, clipped: true }, // starting from here, header is clipped
    },
  },

  // Header clip is fine for the leftEdgeSidebar because it's permanent on lg
  leftEdgeSidebar: {
    autoCollapse: 'lg',
    config: {
      xs: { variant: 'temporary', width: 256 },
      lg: {
        variant: 'permanent',
        width: 256,
        collapsible: true,
        collapsedWidth: 64,
        headerMagnetEnabled: true
      }
    },
  },

  // Header clip is not fine because rightEdgeSidebar is still temporary on lg (it's ok from xl and up)
  rightEdgeSidebar: {
    config: {
      xs: { variant: 'temporary', width: 256 },
      xl: { variant: 'permanent', width: 256 },
    }
  },
};

```

For `leftEdgeSidebar` this is fine: at `lg` breakpoint header is clipped but sidebar is permanent. 

**This configuration however won't work fine for `rightEdgeSidebar`**: there is a "gap"  between `lg` and `xl` when header is clipped and `rightEdgeSidebar` is still temporary.

- Below `lg` (included):

<img width="476" alt="image" src="https://user-images.githubusercontent.com/1532616/210119580-6b1464ba-7407-487a-9dd6-bafbca627df3.png">

- Between `lg` (included) and `xl` (excluded):

<img width="476" alt="image" src="https://user-images.githubusercontent.com/1532616/210119604-a820caaf-1632-4626-a592-1cab0f0d96b0.png">

- Above `xl` (included):

<img width="468" alt="image" src="https://user-images.githubusercontent.com/1532616/210119708-67ae0655-ceb4-4cb5-83e7-84cf25a0fe12.png">

Any idea how to solve this, aside from lowering the breakpoint from `xl `to `lg` for `rightEdgeSidebar`?

**Comment by siriwatknp** [comment]
Layout v5 is no longer maintained. I am working on the migration guide to Layout v6.

https://mui-treasury.com/?path=/docs/layout-v6-configuration-edge-sidebar--docs#right-edge-sidebar
