### ISSUE TITLE
Getting examples working with newer MUI v5 or v6?

### ISSUE THREAD

**Issue by gregfenton** [siriwatknp/mui-treasury#1215]
Are there any decent guides (or working examples/sandboxes) of getting some of the MUI-Treasury code working with newer versions of @MUI ?

For example, I'd like to get https://mui-treasury.com/styles/tabs/#Apple running with MUI v^5.11.0.  I just am not clear as to all the changes required especially around the move away from the deprecated `createStyles()`, and trying to install `@mui-treasury/styles` fails with dependency issues:
```
npm ERR! code ERESOLVE
npm ERR! ERESOLVE unable to resolve dependency tree
npm ERR! 
npm ERR! While resolving: my_app@1.0.0
npm ERR! Found: react@18.2.0
npm ERR! node_modules/react
npm ERR!   react@"18.2.0" from the root project
npm ERR! 
npm ERR! Could not resolve dependency:
npm ERR! peer react@"^16.8.0 || ^17.0.0" from @material-ui/core@4.12.4
npm ERR! node_modules/@material-ui/core
npm ERR!   peer @material-ui/core@"4.x" from @mui-treasury/styles@1.13.1
npm ERR!   node_modules/@mui-treasury/styles
npm ERR!     @mui-treasury/styles@"*" from the root project
```
Things get really deep if `--force` is used . . .

**Comment by danny-faith** [comment]
I'm in the same position as you Greg, I have React 18 and MUI v5. Did you find a solution?

Thank you.

**Comment by Setloth** [comment]
unfortunately stuck with the same- mui latest releases seem to break with the treasury concepts. quite sad

**Comment by siriwatknp** [comment]
The new [mui-treasury](https://mui-treasury.com) is now working with Material UI v5 🎉
