### ISSUE TITLE
component - card - pricing

### ISSUE THREAD

**Issue by borbier** [siriwatknp/mui-treasury#156]
Adding simple pricing card for showing pricing packages
![Pricing Card](https://static.collectui.com/shots/2380690/pricing-large)

**Comment by shakti97** [comment]
Can you explain the action required here?

**Comment by siriwatknp** [comment]
As I mentioned in PR, you can add bg to your showcase by setting config in `metadata`. But I just merged it. If you have time, pull `develop` and try adding bg as `#e9e9e9`.

**Comment by siriwatknp** [comment]
I will close this for now since it is merged, sorry for confusion.
