### ISSUE TITLE
component - arrow - simple

### ISSUE THREAD

**Issue by siriwatknp** [siriwatknp/mui-treasury#165]
## [Read Migration Doc](https://github.com/siriwatknp/mui-treasury/blob/develop/MIGRATION.md)
https://mui-treasury.com/components/carousel/arrow#simple-arrow

![image](https://user-images.githubusercontent.com/18292247/67224357-3632a200-f45b-11e9-8253-b991adcbdf4f.png)

**Comment by 0pdd** [comment]
@siriwatknp the only puzzle [#166](https://github.com/siriwatknp/mui-treasury/issues/166) is solved here.
