### ISSUE TITLE
Contribution guidelines?

### ISSUE THREAD

**Issue by davidedantonio** [siriwatknp/mui-treasury#2]
This is a fantastic project and I would like to participate in the development process.
Can you write a contribution guidelines? Maybe accompanied by a roadmap.

**Comment by siriwatknp** [comment]
Thank you, I really appreciate your help. I will complete contribution guidelines today. Any suggestion is very welcome.

**Comment by siriwatknp** [comment]
@davidedantonio Please check Readme.md

**Comment by davidedantonio** [comment]
@siriwatknp perfect... I'll send you a PR as soon as possible 😃
