### ISSUE TITLE
RTL Support

### ISSUE THREAD

**Issue by shurfa** [siriwatknp/mui-treasury#202]
is there any chance for Supporting  RTL as it is a native feature in Materi-ui ?

**Comment by siriwatknp** [comment]
I think you can follow the documentation about rtl directly since this project is 100% based on Material-UI.

**Comment by siriwatknp** [comment]
Maybe if you can provide your use case, I can help more in detail.

**Comment by rahimasgari** [comment]
Hi,
When i make the layout rtl, according to the Material-UI documentation there is a problem with main content:
in rtl, the drawer is positioned on the right side of the page, so the `<main>` tag which is from `Content` component has margin-left but it must have margin-right instead.
