### ISSUE TITLE
Fix bug production, css missing

### ISSUE THREAD

**Issue by siriwatknp** [siriwatknp/mui-treasury#212]
![image](https://user-images.githubusercontent.com/18292247/69433042-6e384800-0d6d-11ea-81de-1866c0bceba9.png)

**Comment by rohmanhm** [comment]
The same issue happens to me. 
It's rendering correctly for the first time render and then suddenly it breaks.

I tried in the incognito browser also didn't work either.

**Comment by siriwatknp** [comment]
@rohmanhm I found the problem, still fixing it.

**Comment by rohmanhm** [comment]
@siriwatknp I just recheck the website and looks like it fixed now?

![image](https://user-images.githubusercontent.com/7524911/69923317-7cf1ce00-14d6-11ea-81e9-6c441b1a45dc.png)
