### ISSUE TITLE
Convert @materia-ui packages to Peer Dependencies

### ISSUE THREAD

**Issue by aaronhayes** [siriwatknp/mui-treasury#302]
I think it is better to keep all `@material-ui` packages as Peer Dependencies rather than Dependencies. This way we avoid installing multiple instances of packages within our app.

**Comment by siriwatknp** [comment]
Can you explain a little bit about peerDependencies? I am new to this, thanks.

**Comment by aaronhayes** [comment]
Sure with dependencies you can have multiple versions/instances of that dependency installed inside the `node_modules` folder. PeerDependencies avoids this problems by your package essentially saying it only work with certain versions of a package, i.e. `some-package@4.6.0 | some-package@4.7.0. `npm` or `yarn` will print warnings if the correct versions aren't installed.

Without Peer Dependencies: 

```
node_modules/
            |
            +- @material-ui/core v4.8.0
            |
            |
            +- @mui-treasure/components/node_modules/
                                              |
                                              +- @material-ui/core v4.6.0
            |
            |
            +- @mui-treasure/layout/node_modules/
                                              |
                                              +- @material-ui/core v4.6.0
```

With Peer Dependencies, only one version/instance of `@matieral-ui/core` has to be installed.

```
node_modules/
            |
            +- @material-ui/core v4.8.0
            |
            +- @mui-treasure/components/node_modules/
            |
            +- @mui-treasure/layout/node_modules/

```


You can read more here https://nodejs.org/en/blog/npm/peer-dependencies/

**Comment by aaronhayes** [comment]
This can be VERY beneficial in reducing bundle sizes

**Comment by aaronhayes** [comment]
Add a pull request. https://github.com/siriwatknp/mui-treasury/pull/304

**Comment by siriwatknp** [comment]
@all-contributors please add @aaronhayes for performance

**Comment by siriwatknp** [comment]
@all-contributors please add @aaronhayes for code
