### ISSUE TITLE
Attempted import error: 'HeaderOffset' is not exported from '@mui-treasury/layout'.

### ISSUE THREAD

**Issue by Shailu4u** [siriwatknp/mui-treasury#309]

**Comment by siriwatknp** [comment]
Can you provide more info
- what framework are you using?
- any repo that I can reproduce?

**Comment by Egahras** [comment]
Got the same.
Did the following:

1. create-react-app test 
2. cd test
3. yarn add @material-ui/core @material-ui/icons @mui-treasury/layout
4. Edited the test/src/App.js   -> filled in the code i got from https://mui-treasury.com/layout/builder
5. yarn start 
6. got the error:

> Failed to compile
./src/App.js
Attempted import error: 'HeaderOffset' is not exported from '@mui-treasury/layout'.


package.json:
`{
  "name": "test",
  "version": "0.1.0",
  "private": true,
  "dependencies": {
    "@material-ui/core": "^4.8.0",
    "@material-ui/icons": "^4.5.1",
    "@mui-treasury/layout": "^3.1.1",
    "@testing-library/jest-dom": "^4.2.4",
    "@testing-library/react": "^9.3.2",
    "@testing-library/user-event": "^7.1.2",
    "react": "^16.12.0",
    "react-dom": "^16.12.0",
    "react-scripts": "3.3.0"
  },
  "scripts": {
    "start": "react-scripts start",
    "build": "react-scripts build",
    "test": "react-scripts test",
    "eject": "react-scripts eject"
  },
  "eslintConfig": {
    "extends": "react-app"
  },
  "browserslist": {
    "production": [
      ">0.2%",
      "not dead",
      "not op_mini all"
    ],
    "development": [
      "last 1 chrome version",
      "last 1 firefox version",
      "last 1 safari version"
    ]
  }
}
`

**Comment by toutouli** [comment]
Got the same.
Attempted import error: 'HeaderOffset' is not exported from '@mui-treasury/layout'.
Attempted import error: 'useSidebarStyles' is not exported from '@mui-treasury/layout'.
Attempted import error: 'useHeaderStyles' is not exported from '@mui-treasury/layout'.

**Comment by kimskovhusandersen** [comment]
Got the same issue: 
Did the following: 

1. create-react-app portfolio
2. cd portfolio
3. npm i @material-ui/core @material-ui/icons @mui-treasury/layout --save
4. npm start

got the error:
Failed to compile
./src/App.js
Attempted import error: 'HeaderOffset' is not exported from '@mui-treasury/layout'.


package.json:
`{
    "name": "portfolio",
    "version": "0.1.0",
    "private": true,
    "dependencies": {
        "@material-ui/core": "^4.9.0",
        "@material-ui/icons": "^4.5.1",
        "@mui-treasury/layout": "^3.3.2",
        "@testing-library/jest-dom": "^4.2.4",
        "@testing-library/react": "^9.4.0",
        "@testing-library/user-event": "^7.2.1",
        "react": "^16.12.0",
        "react-dom": "^16.12.0",
        "react-router-dom": "^5.1.2",
        "react-scripts": "3.2.0",
        "typeface-roboto": "0.0.75"
    },
    "scripts": {
        "start": "react-scripts start",
        "build": "react-scripts build",
        "test": "react-scripts test",
        "eject": "react-scripts eject"
    },
    "eslintConfig": {
        "extends": "react-app"
    },
    "browserslist": {
        "production": [
            ">0.2%",
            "not dead",
            "not op_mini all"
        ],
        "development": [
            "last 1 chrome version",
            "last 1 firefox version",
            "last 1 safari version"
        ]
    }
}
`

**Comment by codsane** [comment]
@kimskovhusandersen Ever manage to get this resolved? Few weeks later and I'm getting identical results.

**Comment by kimskovhusandersen** [comment]
> @kimskovhusandersen Ever manage to get this resolved? Few weeks later and I'm getting identical results.

I ended up making HeaderOffset component and using that to offset the header, but I guess there are more elegant solutions. 

`import React from "react";
import { makeStyles } from "@material-ui/core/styles";

const useStyles = makeStyles(theme => ({
  HeaderOffset: {
    width: "100%",
    minHeight: theme.header.minHeight,
    backgroundColor: "transparent"
  }
}));

const HeaderOffset = props => {
  const classes = useStyles();
  return <div className={classes.HeaderOffset}></div>;
};

export default HeaderOffset;
`

**Comment by alexichepura** [comment]
This is not fixed:
https://github.com/siriwatknp/mui-treasury/blob/master/packages/mui-layout/src/components/index.js

Temp workaround
```ts
import HeaderOffset from "@mui-treasury/layout/components/HeaderOffset"
```
For typescript need to declare a module somewhere
```ts
declare module "@mui-treasury/layout/components/HeaderOffset"
```
