### ISSUE TITLE
Not able to set Content at full screen height

### ISSUE THREAD

**Issue by legege** [siriwatknp/mui-treasury#321]
I'm trying to set Content to take full screen height and it seems impossible. In my case, the content is a React Grid with Virtual Table designed to take full height (https://devexpress.github.io/devextreme-reactive/react/grid/docs/guides/virtual-scrolling/#fill-the-container).

Here is an example:
https://codesandbox.io/s/material-ui-layout-c1ojz

**Comment by siriwatknp** [comment]
@legege `height: 100%` will not work, I think you need `height: calc(100% - 64px)`

**Comment by siriwatknp** [comment]
I will close this since it is not related to layout library

**Comment by legege** [comment]
But still, how to make the content 100%? Even without the Grid library, setting height to `calc(100%-64px)` doesn't work.

https://codesandbox.io/s/material-ui-layout-isi15

**Comment by legege** [comment]
Working example thanks to your Messenger demo: https://codesandbox.io/s/material-ui-layout-xp8oi
