### ISSUE TITLE
ThemeProvider is not exported from root.js

### ISSUE THREAD

**Issue by drtobbyas** [siriwatknp/mui-treasury#367]
./node_modules/@mui-treasury/layout/components/Root.js
Attempted import error: 'ThemeProvider' is not exported from '@material-ui/core/styles'.
^C

**Comment by siriwatknp** [comment]
Can you provide more detail?
- version of mui-treasury/layout
- may be repo | codesandbox that I can reproduce

**Comment by siriwatknp** [comment]
@drtobbyas I think I know why you got error. Please try upgrade @material-ui/core to latest, I think that will solve.

**Comment by drtobbyas** [comment]
I have resolved it.  But notably the documentation is a bit confusing.
There are some packages that were not natively exported from the module but
used as if they were exported.  Many people would prefer to copy and paste
the doc example to test a package or import using repl.it while testing a
new package.
All the same great work  and thanks for the reply.
Regards

**Comment by siriwatknp** [comment]
@drtobbyas any suggestion on how to make it better for other people?
