### ISSUE TITLE
Phishing warning when accesing "Theme" tab on your website

### ISSUE THREAD

**Issue by elvenking** [siriwatknp/mui-treasury#387]
Hello Siriwat, firstly i would like to say thank you for your awesome work !
I really like mui-treasury and using it in one of my projects.

I would like to report strange behaviour of mui-treasury website.

When I access "Theme" tab (https://deprecate.mui-treasury.com/brands/peapods) I am receiving a warning from my Antivirus software about phishing attempt.

Can you please do something about it ? 

<img width="1665" alt="phishing" src="https://user-images.githubusercontent.com/3741866/71998626-44b17e00-3240-11ea-9913-5dfdced62aea.png">

**Comment by siriwatknp** [comment]
@elvenking got it, will use another image on that.

**Comment by siriwatknp** [comment]
Can you check the website again?
![image](https://user-images.githubusercontent.com/18292247/72536394-c2166780-38ac-11ea-8643-3930b1890d7d.png)

**Comment by elvenking** [comment]
Now it looks fine, i don't receive the alert. Thank you
