### ISSUE TITLE
SSR Layout Context problem

### ISSUE THREAD

**Issue by tokdaniel** [siriwatknp/mui-treasury#391]
## *Description*
I'm using next.js and SSR seems to misbehave regarding LayoutContext.
```code
import useScreenComparison from './useScreenComparison';
export default ((ctx = {}) => {
  const {
    insetHiddenBreakpoint,
    insetHiddenDisabled,
    sidebar
  } = ctx;
  const values = useScreenComparison(insetHiddenBreakpoint);
  return _extends({}, values, {
    insetHiddenDisabled,
    displayedAboveBreakpoint: ---> sidebar.inset && values.isTargetAbove && !insetHiddenDisabled,
    displayedBelowBreakpoint: ---> sidebar.inset && values.isTargetDown && !insetHiddenDisabled
  });
});
```
the marked things are evaluating to undefined, probably because ctx is not there on the server-side.

## *What* is affected by this bug?
The layout breaks with Footer.js  error

## *When* does this occur?
If you import the provided code with the mui-treasury layout-builder in _app

## *Where* on the platform does it happen?
I've tried it on nextjs, but this could happen anytime SSR is utilized

## *How* do we replicate the issue?
1. Create a nextjs app
2. Install @mui-treasury/layout
3. Add your builder-generatted code into _app

## Expected behavior (i.e. solution)
a simple 
```code
sidebar && sidebar.inset && values.isTargetAbove && !insetHiddenDisabled,
``` 
would do the trick I think, but LayoutContext should probably be investigated further more.

**Comment by siriwatknp** [comment]
The merge request should fix the problem
