### ISSUE TITLE
typescript support (for layout package)

### ISSUE THREAD

**Issue by siriwatknp** [siriwatknp/mui-treasury#398]

**Comment by venegasalejandro** [comment]
Hi, I would like to take a crack at adding the declarations. I believe you want to bundle the typings within the package, correct? (As opposed to placing them in DefinitelyTyped)

**Comment by siriwatknp** [comment]
@venegasalejandro Hi, thanks a lot for your contribution. I have to say I am not familiar with typescript. What is your suggestion?

**Comment by ceefour** [comment]
@siriwatknp do you consider changing (part of) mui-treasury codebase to compiled with TypeScript? This way TypeScript users get always-updated typings for free, and JavaScript users can use the library normally.

It can be done gradually, starting from, I agree with you and @venegasalejandro , the layout package.

**Comment by venegasalejandro** [comment]
I think we should follow Material-UI's example: they keep all their source code in Javascript, but make sure to update Typescript definitions before releases, and of course all the Typescript definitions are packaged within their several npm packages.

**Comment by videni** [comment]
Material-UI has a quite large codebase, it will takes lots of time do migration, they provide typescript definitions is a compromise solution,  since this project is just started, I strongly suggest  writing it with Typescript. the learning curve for Typescript is not  that steep.

**Comment by venegasalejandro** [comment]
@siriwatknp Hey thanks for doing the merge! I've been sort of busy at work and haven't been able to check in. Is there still interest in converting the package to be completely Typescript (rather than having the declarations separate)? If so, I would love to contribute once I have some free time.

**Comment by siriwatknp** [comment]
@venegasalejandro That's awesome. However, I think the current version has some downside.
1. It does not work well with server side frame work. ex. NextJS, Gatsby
2. It use too much javascript instead of css for determining width &margin, therefore performance is bad (from what I measure with lighthouse)
I am thinking about rewriting the lib to move toward css approach but will remain the same api as much as possible, what do you think?

**Comment by verbumfeit** [comment]
Following the [tutorial](https://mui-treasury.com/layout/) with TypeScript doesn't work. The module can't be found, and I don't think the current layout package contains the .d.ts files. Anybody know what's going on?

**Comment by na-ji** [comment]
> Following the [tutorial](https://mui-treasury.com/layout/) with TypeScript doesn't work. The module can't be found, and I don't think the current layout package contains the .d.ts files. Anybody know what's going on?

See #624
