### ISSUE TITLE
use prettier

### ISSUE THREAD

**Issue by mikestaub** [siriwatknp/mui-treasury#44]
This tool is becoming a standard and can help keep the code readable and maintainable.

It also saves developers tons of time wasted on formatting code.

**Comment by siriwatknp** [comment]
I did set prettier. Is it not correct?

![image](https://user-images.githubusercontent.com/18292247/58538511-821c4a80-821f-11e9-8e36-f017e7a5d7f7.png)

**Comment by siriwatknp** [comment]
For me, I use webStorm and press cmd + P, then prettier will do the job.

**Comment by mikestaub** [comment]
I will commit my .vscode settings if you don't mind. It formats on save.

**Comment by siriwatknp** [comment]
@mikestaub thanks a lot

**Comment by mikestaub** [comment]
@siriwatknp https://github.com/siriwatknp/mui-treasury/pull/76
