### ISSUE TITLE
Issue with testing-library/react and jest

### ISSUE THREAD

**Issue by BoringOwlCompany** [siriwatknp/mui-treasury#466]
`import React from "react";
import { render } from "@testing-library/react";
import App from "./App";

test("Material text should be inside app", () => {
  const { getByText } = render(<App />);
  const linkElement = getByText("Material");
  expect(linkElement).toBeInTheDocument();
});`

While running the most basic test I receive an error

` \node_modules\@mui-treasury\layout\index.js:1
    ({"Object.<anonymous>":function(module,exports,require,__dirname,__filename,global,jest){export * from './components';
                                                                                             ^^^^^^

    SyntaxError: Unexpected token export

      17 | import Container from "@material-ui/core/Container";
      18 |
    > 19 | import {
         | ^
      20 |   Root,
      21 |   Header,
      22 |   Sidebar,

      at ScriptTransformer._transformAndBuildScript (node_modules/@jest/transform/build/ScriptTransformer.js:537:17)
      at ScriptTransformer.transform (node_modules/@jest/transform/build/ScriptTransformer.js:579:25)
      at Object.<anonymous> (src/containers/Layout.js:19:1)

Test Suites: 1 failed, 1 total
Tests:       0 total
Snapshots:   0 total
Time:        7.771s
Ran all test suites related to changed files.

FAIL src/App.test.js
`

**Comment by siriwatknp** [comment]
#472 
Because @mui-treasury/layout is not transpiled as cjs and contain es6 code. You need to add `babel-jest` to transpile it. I add example how to config jest in create-react-app.

```
// in package.json
"jest": {
    "transform": {
      "\\.(js|ts|tsx)?$": "babel-jest"
    },
    "transformIgnorePatterns": [
      "/^((?!node_modules/@mui-treasury/layout$).)*$/"
    ]
  },
```
