### ISSUE TITLE
Outline Select I

### ISSUE THREAD

**Issue by siriwatknp** [siriwatknp/mui-treasury#539]
![image](https://user-images.githubusercontent.com/18292247/76324961-5505d800-6319-11ea-9bed-ef296efc8339.png)

**Comment by pacurtin** [comment]
@siriwatknp I'm starting on this. Should I do 5 different Select Styles? Also should we put the datepicker design in its own category on the website?

**Comment by pacurtin** [comment]
I think the "Download" design and 3 dot icon designs are [Menus](https://material-ui.com/components/menus/) not Selects.

The datepicker design is like a mix of [Select](https://material-ui.com/components/selects/) and [Datepicker](https://material-ui.com/components/pickers/). So should this go under Styles Custom Component section?

I'm not really sure how to make the "Unit" design that lets you type in the input of the select. But I do think it belongs in Select category.

The "sort by name" select seems the most straight forward. I'll do that first.

**Comment by pacurtin** [comment]
I have completed one of the five designs:

<img width="396" alt="Screen Shot 2020-05-12 at 9 05 00 AM" src="https://user-images.githubusercontent.com/17761806/81701926-424e7300-9430-11ea-8a3c-ba57ad3ac743.png">

Should I create a pull request for this and create 4 more github issues to track the other designs? @siriwatknp

**Comment by siriwatknp** [comment]
I agree with you. Let's open PR for this design.

**Comment by siriwatknp** [comment]
I think the download one is quite similar, so you can open another issue with the name you like!

**Comment by pacurtin** [comment]
Sounds good. I'll do that now.
