### ISSUE TITLE
Minimal Select

### ISSUE THREAD

**Issue by siriwatknp** [siriwatknp/mui-treasury#540]
![image](https://user-images.githubusercontent.com/18292247/76325127-8da5b180-6319-11ea-914f-7e896079ad6d.png)

**Comment by pacurtin** [comment]
I'm going to start work on this.

**Comment by pacurtin** [comment]
@siriwatknp I think we can close this ticket.

**Comment by siriwatknp** [comment]
@pacurtin sure, thanks. can I have your twitter, will share this new component.
