### ISSUE TITLE
[Layout] Variable naming grammar mistake: "opened" --> "open"

### ISSUE THREAD

**Issue by lamuertepeluda** [siriwatknp/mui-treasury#555]
Hi guys, first of all great job and thanks for creating this library!

I just found out a little grammar weirdness (I'm not myself English mothertongue, however...)

I see that in layoutContex you named the state variable for the drawer "opened", but it should rater be "open", as this is the adjective whose converse is "closed" (see https://www.wordreference.com/definition/open)

https://github.com/siriwatknp/mui-treasury/blob/master/packages/mui-layout/src/core/layoutContext.js#L20

I believe that line should be

```js
const [open, setOpen] = React.useState(initiallyOpen);
```

and so other "opened"-related variable names. Also "initialOpened" should become "initiallyOpen".
I believe good variables naming makes the code easier to be read :)

Cheers

**Comment by siriwatknp** [comment]
@lamuertepeluda Wow, I was wrong the whole time! thanks for your feedback. I will fix it asap.

**Comment by siriwatknp** [comment]
This fix still expose opened for previous usage (will be removed in the next major change). From now on please use open instead.
