### ISSUE TITLE
[Layout] No Typescript definitions found

### ISSUE THREAD

**Issue by frbrz** [siriwatknp/mui-treasury#624]
After simply doing `npx create-react-app material --typescript`, `yarn add @material-ui/core @mui-treasury/layout @mui-treasury/mockup` and copying the code found in [Control Sidebar](https://mui-treasury.com/layout/basic-examples/control-sidebar?bgColor=e9e9e9&primary=36338E&accent=ff9600), no typescript definitions are found for any of the packages of mui-treasury.

```
Could not find a declaration file for module '@mui-treasury/layout'. '/home/username/Documents/Code/material/node_modules/@mui-treasury/layout/index.js' implicitly has an 'any' type.
  Try `npm install @types/mui-treasury__layout` if it exists or add a new declaration (.d.ts) file containing `declare module '@mui-treasury/layout';`
```

Any ideas?

**Comment by na-ji** [comment]
The typescript definitions are not published, that's why we can't find them.

**Comment by siriwatknp** [comment]
I will fix that tomorrow, thanks for opening this issue.

**Comment by na-ji** [comment]
@siriwatknp Is it possible to publish this fix please?
