### ISSUE TITLE
[Layout] Support For Swipeable Drawers 

### ISSUE THREAD

**Issue by suren179** [siriwatknp/mui-treasury#630]
Hi,

Can we have support for Swipeable Drawers (Already introduced material UI : [Link](https://material-ui.com/api/swipeable-drawer/) )

Thanks In Advance

**Comment by siriwatknp** [comment]
@suren179 Yep, sure. will add asap. I would like some feedback about the layout library, how was it?

**Comment by suren179** [comment]
Thanks a lot. Really appreciate quick response.
The layout library has really helped us quickly implement the responsive navigation in our application. Even though the library is pretty new, I could see a lot engagement from you guys and that was the reason we felt comfortable using this. Keep up the good work 👍.
Plus the sample code made our lives much easier.

Someday we would really like to contribute to this awesome library (couldn't do it right now as we have a lot on our plate and don't have any spare time).

**Comment by siriwatknp** [comment]
https://mui-treasury.com/layout/api-reference/swipeable-sidebar
will close this issue once v4 is in rc.
