### ISSUE TITLE
Duplicate identifier in layout generator for ChevronLeftIcon

### ISSUE THREAD

**Issue by vivshaw** [siriwatknp/mui-treasury#64]
Hello, in the generated code for a Layout using chevron icons, there are two different lines that import as ChevronLeftIcon, and nothing that imports as ChevronRightIcon. This causes these layouts to throw errors.

I will submit a pull request shortly.

**Comment by siriwatknp** [comment]
@vivshaw Have you use the Layout components? What do you think?
