### ISSUE TITLE
Installation problem

### ISSUE THREAD

**Issue by JfrA** [siriwatknp/mui-treasury#659]
Have run npx create-react-app
npm install @material-ui/core

Searched google found also this:
 npm install @mui-treasury/mockup
 npm install @mui-treasury/styling
 npm install @mui-treasury/theme
 npm install @mui-treasury/compontents
 npm install @mui-treasury/layout

Add all the files from the sandbox to my src folder, but still getting this (Loong) error:

Error: You are calling withTheme(Component) with an undefined component.
You may have forgotten to import it.

withTheme
node_modules/@material-ui/styles/esm/withTheme/withTheme.js:15
./src/Layout/Header.js
src/Layout/Header.js:172
  169 |   menuIcon: ""
  170 | };
  171 | 
> 172 | export default withTheme()(withStyles(styles, { name: "MuiHeader" })(Header));
  173 | View compiled
__webpack_require__
/Users/jonasandersson/Codes/REACT/todo/webpack/bootstrap:784
  781 | };
  782 | 
  783 | // Execute the module function
> 784 | modules[moduleId].call(module.exports, module, module.exports, hotCreateRequire(moduleId));
      | ^  785 | 
  786 | // Flag the module as loaded
  787 | module.l = true;View compiled
fn
/Users/jonasandersson/Codes/REACT/todo/webpack/bootstrap:150
  147 | 		);
  148 | 		hotCurrentParents = [];
  149 | 	}
> 150 | 	return __webpack_require__(request);
      | ^  151 | };
  152 | var ObjectFactory = function ObjectFactory(name) {
  153 | 	return {View compiled
./src/Layout/index.js
src/Layout/index.js:1
> 1 | export { default as Header } from "./Header";
  2 | export { default as Content } from "./Content";
  3 | export { default as Root } from "./Root";
  4 | export { default as Nav } from "./Nav";View compiled
__webpack_require__
/Users/jonasandersson/Codes/REACT/todo/webpack/bootstrap:784
  781 | };
  782 | 
  783 | // Execute the module function
> 784 | modules[moduleId].call(module.exports, module, module.exports, hotCreateRequire(moduleId));
      | ^  785 | 
  786 | // Flag the module as loaded
  787 | module.l = true;View compiled
fn
/Users/jonasandersson/Codes/REACT/todo/webpack/bootstrap:150
  147 | 		);
  148 | 		hotCurrentParents = [];
  149 | 	}
> 150 | 	return __webpack_require__(request);
      | ^  151 | };
  152 | var ObjectFactory = function ObjectFactory(name) {
  153 | 	return {View compiled
./src/index.js
http://localhost:3000/static/js/main.chunk.js:767:84
__webpack_require__
/Users/jonasandersson/Codes/REACT/todo/webpack/bootstrap:784
  781 | };
  782 | 
  783 | // Execute the module function
> 784 | modules[moduleId].call(module.exports, module, module.exports, hotCreateRequire(moduleId));
      | ^  785 | 
  786 | // Flag the module as loaded
  787 | module.l = true;View compiled
fn
/Users/jonasandersson/Codes/REACT/todo/webpack/bootstrap:150
  147 | 		);
  148 | 		hotCurrentParents = [];
  149 | 	}
> 150 | 	return __webpack_require__(request);
      | ^  151 | };
  152 | var ObjectFactory = function ObjectFactory(name) {
  153 | 	return {View compiled
(anonymous function)
http://localhost:3000/static/js/main.chunk.js:934:37
__webpack_require__
/Users/jonasandersson/Codes/REACT/todo/webpack/bootstrap:784
  781 | };
  782 | 
  783 | // Execute the module function
> 784 | modules[moduleId].call(module.exports, module, module.exports, hotCreateRequire(moduleId));
      | ^  785 | 
  786 | // Flag the module as loaded
  787 | module.l = true;View compiled
checkDeferredModules
/Users/jonasandersson/Codes/REACT/todo/webpack/bootstrap:45
  42 | 	}
  43 | 	if(fulfilled) {
  44 | 		deferredModules.splice(i--, 1);
> 45 | 		result = __webpack_require__(__webpack_require__.s = deferredModule[0]);
     | ^  46 | 	}
  47 | }
  48 | View compiled
webpackJsonpCallback
/Users/jonasandersson/Codes/REACT/todo/webpack/bootstrap:32
  29 | 	deferredModules.push.apply(deferredModules, executeModules || []);
  30 | 
  31 | 	// run deferred modules when all chunks ready
> 32 | 	return checkDeferredModules();
     | ^  33 | };
  34 | function checkDeferredModules() {
  35 | 	var result;View compiled
global code
http://localhost:3000/static/js/main.chunk.js:1:65
This screen is visible only in development. It will not appear if the app crashes in production.
Open your browser’s developer console to further inspect this error.  Click the 'X' or hit ESC to dismiss this message.

**Comment by siriwatknp** [comment]
Can you provide the github repo or codesandbox that I can take a look? I cannot investigate with this error. It could be the version or bug.

**Comment by JfrA** [comment]
I started out from this page: https://deprecate.mui-treasury.com/components/layout
and followed that guide.

the sandbox is the one from the link in that page: https://codesandbox.io/s/6xnlp688v3

Haven't done anything else.

Am I missing something here?

**Comment by siriwatknp** [comment]
I see. That link is deprecated, please checkout this link instead.

**For dashboard layout**
https://mui-treasury.com/layout/tutorials/dashboard-layout/

**For blog layout**
https://mui-treasury.com/layout/tutorials/blog-layout/

**Comment by JfrA** [comment]
Ahh, ok my bad.

**Comment by siriwatknp** [comment]
Let me know if you still stuck at some step.
