### ISSUE TITLE
Documentation seems outdated for getting started with Material-UI extended components

### ISSUE THREAD

**Issue by pacurtin** [siriwatknp/mui-treasury#663]
Hi @siriwatknp. Very cool project you have here! 

I noticed the following in the getting started docs though:

https://mui-treasury.com/components
- Should mention need `npm install @material-ui/core` for Material-UI Extended section
- `import BirthdayTextField from @mui-treasury/components/textField/birthday` doesn't seem to be a valid import?  Needs to be `import Birthday from '@mui-treasury/components/textField/birthday'
` instead?

https://mui-treasury.com/components/text-field/birthday
- needs a link to code (<> button)

https://mui-treasury.com/components/text-field
-Not responsive enough/ needs scroll on Mac Chrome. When viewing the large screen preview the buttons on the top left go off the screen and cant be scrolled up to:
<img width="1377" alt="Screen Shot 2020-04-13 at 12 24 00 PM" src="https://user-images.githubusercontent.com/17761806/79142837-c7872f00-7d81-11ea-9eb5-5a190311cf75.png">

I'm happy to open a pull request to fix these things.

**Comment by siriwatknp** [comment]
@pacurtin Feel free to improve and send PR!, thanks a lot. Currently I'm working on Layout v4 #660 so I will not be able to fix other issues until mid-May but happy to review PR.

**Comment by siriwatknp** [comment]
And agreed, I realised documentation is number 1 priority and I will keep improving that.
