### ISSUE TITLE
Starter for Next.js is not working (solution provided)

### ISSUE THREAD

**Issue by barthicus** [siriwatknp/mui-treasury#665]
Running fresh starter for a next.js from [repo ](https://github.com/siriwatknp/mui-treasury/tree/master/starters/nextjs) stops with this error:

`TypeError: modules.map is not a function`

It is caused be a plugin `next-transpile-modules` and the [new invocation method](https://github.com/martpie/next-transpile-modules/releases/tag/3.0.0).

The whole problem can be easily fixed updating next.config.js to this:

```
// next.config.js
const withTM = require('next-transpile-modules')(['@mui-treasury/layout', '@mui-treasury/mockup']);

module.exports = withTM({});
```

Hope it's gonna helps someone else.
Cheers!

**Comment by siriwatknp** [comment]
Would you like to send a PR?

**Comment by barthicus** [comment]
> Would you like to send a PR?

I just did. It was my first PR in JS world. I hope I didn't do any mistake there :)

**Comment by siriwatknp** [comment]
@barthicus Thanks so much! Welcome to JS world, haha.
