### ISSUE TITLE
Can't find Components

### ISSUE THREAD

**Issue by AndreMaciel66** [siriwatknp/mui-treasury#693]
Hey there, I'm quite new in react/material/mui-treasury and I'm trying to use some of your components but I'm receiving this error:

```sh
./src/App.js
Module not found: Can't resolve '@mui-treasury/components/' in '/Users/a116822/examples/mui-treasury/src'
```
I'm following the components page tutorial, and of course, I've used `yarn add @mui-treasury/components`

I have no idea what I'm doing wrong... but the components folder in `node_modules\@mui-treasury` have no folders inside.

**Comment by siriwatknp** [comment]
can I see your package.json?

**Comment by siriwatknp** [comment]
@AndreMaciel66 My mistake for publishing empty library. If you upgrade to these version. It should work.
 - @mui-treasury/components@1.0.4
 - @mui-treasury/layout@4.0.0-alpha.3
 - @mui-treasury/mockup@1.0.4
 - @mui-treasury/styles@1.1.3

**Comment by AndreMaciel66** [comment]
Tks for letting me know?
