### ISSUE TITLE
Interaction with Header component

### ISSUE THREAD

**Issue by workboxsoftware** [siriwatknp/mui-treasury#697]
I was wondering if there are any examples of how to dynamically change the Header.  For example, some screens need a Search Component - or a Save button, etc.  Also, in your current example you have Search component - how does one access what the user has typed?  

Is the recommended way to add Context above your Layout component and communicate that way between Header and my app screens?

**Comment by siriwatknp** [comment]
You can totally do that. The implementation depends on your router but the concept is the same and it is not relate to layout.

ex.
```js
const App = () => {
  const { location } = useLocation() // react-router in this case
  return (
    <Root config={config}>
      <Header>
        {location.pathname === '/' ? <SpecificHomepageHeader /> : <GeneralHeader />
      </Header>
      ...
    </Root>
  )
}

```

**Comment by siriwatknp** [comment]
Please help comment in #699

**Comment by workboxsoftware** [comment]
Thanks Siriwat - I can use your suggestion for changing the Header based on the Route.  But can you suggest how the Route should communicate with the Header?  Enable/disable,getClickEvent on a button,  get the contents of the search box, etc.  

Thanks,
Bob

**Comment by siriwatknp** [comment]
If you need to communicate between component, you need a state that is higher than these components. The state can be at App level or you can use Context to share between component. Last choice is to use javascript like get elementById and do something with the DOM.

If you can share your requirement in detail, I might be able to explain it better. However, I don't think this involve mui-layout, so I will close for now.

**Comment by workboxsoftware** [comment]
Thanks Siriwat - I'm fine with that answer.  I just wanted to know if there was anything build it - or some solution I was missing.
