### ISSUE TITLE
headerStyles is not defined

### ISSUE THREAD

**Issue by malkavsheir** [siriwatknp/mui-treasury#698]
Attempting to follow the Dashboard tutorial, but I am encountering the error "headerStyles" is not defined. I looked into the treasury components for the Root component, and I do see that it exists there so I am not sure why this is occurring. 

You can see my project here:
https://codesandbox.io/s/falling-dream-kmw5q

**Comment by siriwatknp** [comment]
Sorry for that, I will update the doc.`headerStyles` is one of render props (same as sidebarStyles)
```
function App() {
  return (
    <Root theme={customTheme} config={config}>
      {({ sidebarStyles, headerStyles }) => (
        <>
          <Header>
            <Toolbar>
              <SidebarTrigger className={headerStyles.leftTrigger}>
                <SidebarTriggerIcon />
              </SidebarTrigger>
              Header
            </Toolbar>
          </Header>
          <Sidebar>
            <div className={sidebarStyles.container}>
              <NavHeaderMockUp />
              <NavContentMockUp />
            </div>
            <CollapseBtn className={sidebarStyles.collapseBtn}>
              <CollapseIcon />
            </CollapseBtn>
          </Sidebar>
          <Content>
            <ContentMockUp />
          </Content>
          <Footer>
            <FooterMockUp />
          </Footer>
        </>
      )}
    </Root>
  );
}
```

**Comment by siriwatknp** [comment]
Please help comment in #699

**Comment by debihiga** [comment]
Hi, today I tried the Dashboard tutorial and I just want to add that the following things are needed if you want to follow the steps, using @mui-treasury/layout v3.3.2 (for v4 it didn't work for me):
1. @material-ui/icons should be added in the install packages section. If not, it will throw this error:
```
./node_modules/@mui-treasury/layout/components/CTA/SidebarTrigger.js
Module not found: Can't resolve '@material-ui/icons/KeyboardArrowLeftRounded' in 'C:\Users\user\Desktop\Debi\Github\my-layout\node_modules\@mui-treasury\layout\components\CTA'
Compiling...
Failed to compile.
```
2. It does not work for  @mui-treasury/mockup@1.0.3 (latest) but it does for  @mui-treasury/mockup@1.0.1. For 1.0.3 it throws this error:
`./src/App.js
Module not found: Can't resolve '@mui-treasury/mockup/layout' in 'C:\Users\user\Desktop\Debi\Github\my-layout\src'`

**Comment by malkavsheir** [comment]
Thank you Siriwat! That solved the issue.

@debihiga - I also found this, but was able to resolve based on trial of different versions in the codesandbox until I found one that worked.
