### ISSUE TITLE
[RFC] Layout Documentation

### ISSUE THREAD

**Issue by siriwatknp** [siriwatknp/mui-treasury#699]
For incoming layout v4, What are documentation that you want to see?
This is the current list that I will create.
#### Tutorial #703 
- Dashboard layout
- Blog layout
#### Framework Setup #704 
- Create react app
- Gatsby
- Next
#### Advanced #705 
- mutate preset
- dynamic config
- control sidebar
- hide sidebar on path

**Comment by workboxsoftware** [comment]
I'd love to see an example that's integrated with react-router that uses some of the features of a real-life app.  For instance, where different routes require different headers and sidebars - and show how the route can best communicate with these components to update the components (enable/disable), get events and get contents of text fields (e.g., a search text box).

**Comment by aress31** [comment]
I would love to see following:

- How to integrate the `Material-UI nested menu` from the `mui-treasury` within the `Sidebar` with proper working example of routes.
- How to support multiple `Headers`, for instance, a top one displaying various contact information or an important message that gets larger on scroll and a second one that display the usual navigation options that hides on scroll events.
- Also similarly to some other libraries, namely https://components-extra.netlify.app/components/footer, it would be nice if the `Footer` component from the `layout` lib offered similar features to enable for quick and beautiful - using your preset approach -  design of web footers.

I think that the above would cover all my needs - at the minute - to quickly bootstrap Material Ui based projects.

Once again, amazing works for creating this lib @siriwatknp, it is a brilliant lib!

**Comment by zizipoil** [comment]
to add on top of @workboxsoftware comment:

I am new to this library and I am currently struggling to use NestedMenu with react-router.

Sparing you the details, I would love to have access to a `onClicked(key, isLeaf)` event or a complete example about how to use NestedMenu along with react-router.

Thanks a bunch for this great library though!
