### ISSUE TITLE
[Doc] setup Layout with these frameworks

### ISSUE THREAD

**Issue by siriwatknp** [siriwatknp/mui-treasury#704]
Due to #699 
- [x] [Create react app](https://github.com/mui-treasury/cra-mui-layout)
- [x] NextJS
- [x] Gatsby

**Comment by siriwatknp** [comment]
@barthicus do you want to own the documentation for NextJS. I created a separate repo for it (it is empty right now) what do you think if we move starter to its own repo so that people can pull and try out. https://github.com/mui-treasury/nextjs-mui-layout

**Comment by barthicus** [comment]
> @barthicus do you want to own the documentation for NextJS. I created a separate repo for it (it is empty right now) what do you think if we move starter to its own repo so that people can pull and try out. https://github.com/mui-treasury/nextjs-mui-layout

Hi @siriwatknp Glad that you mentioned me 😊 I could try but I'm not sure I'm experienced enough in maintaining open source project using all the good practices like tests and writing good docs that are probably required. All I can offer is to deliver some working example using next.js and mui layout.

If you are ok with this I can try to write it some time but can't give some date. I'm really lacking spare hours after work in this difficult covid situation.

Btw: thanks for this lib, I really liked it and used it in my CRA project at work 💪

**Comment by siriwatknp** [comment]
Thank you so much. take some rest 😁. will add your face for now, let me know if you need any help.

**Comment by siriwatknp** [comment]
Sorry for taking your task 🙏 @barthicus

**Comment by siriwatknp** [comment]
![image](https://user-images.githubusercontent.com/18292247/81575790-a42bc000-93d1-11ea-807d-8d1ca599a5f6.png)
