### ISSUE TITLE
Global Layout configuration from JSON

### ISSUE THREAD

**Issue by aress31** [siriwatknp/mui-treasury#712]
With the v3, I used to globally configure my layout with the help of a `JSON file` that looks like:
```
export default {
  heightAdjustmentDisabled: false,
  md: {
    content: {
      persistentBehavior: 'fit',
    },
    footer: {
      persistentBehavior: 'fit',
    },
    header: {
      clipped: false,
      offsetHeight: 64,
      persistentBehavior: 'fit',
      position: 'sticky',
    },
    sidebar: {
      anchor: 'left',
      variant: 'permanent',
      width: 256,
    },
  },
  sm: {
    content: {
      persistentBehavior: 'fit',
    },
    footer: {
      persistentBehavior: 'fit',
    },
  --- SNIP ---
};
```

With the  V4, is it still possible to use this centralised and easily transferable approach or do we have to use the new `Builder`?

**Comment by siriwatknp** [comment]
@aress31 Thanks for calling this out. I think it is a good idea to support JSON file in v4 because internally it stores as plain object but the schema is quite different from v3 for clarity and better design. I think there are 2 tasks that I see here.

1. support JSON config.
2. how to upgrade to v4 with least afford

What do you think?

**Comment by aress31** [comment]
That sounds like a good plan to me!

I am in the middle of upgrading my application to use the `v4` of `mui-treasury/layout` and I have noticed that the `scheme` is not very well documented at the minute - I am aware that you are in the middle of the doc refactoring - but just reminding that it would be useful when you have some time to add to the documentation the details of the parameters expected by the `Builder`. 😁

For example, I do not really know if the following would be working:
```
scheme.configureContent((builder) => {
  builder.create('content_id', { persistentBehavior: 'fit' });
});

scheme.configureFooter((builder) => {
  builder.create('footer_id', { persistentBehavior: 'fit' });
});
```

**Comment by siriwatknp** [comment]
@aress31 totally agree, please do not upgrade your production code at this moment and wait until the API reference is published. I will assign you as a reviewer for that documentation 🙏

**Comment by aress31** [comment]
@siriwatknp sure thing!
