### ISSUE TITLE
Header default config not working

### ISSUE THREAD

**Issue by aress31** [siriwatknp/mui-treasury#714]
I have noted that using the `Builder` to configure the default `Header` behaviour for all breakpoints -see code snippet below - yield the error below:

```
scheme.configureHeader((builder) => {
  builder.create('header_id', {
    offsetHeight: 64,
    position: 'sticky',
  });
});
```

![image](https://user-images.githubusercontent.com/11601622/80796623-91c2b280-8b97-11ea-8c72-e199adf7a471.png)

As far as my understanding goes, the `create` method takes a `unique ID` and an initial configuration. This approach is very handy and works just fine for the `EdgeSidebar` - see code below - so I am guessing it might be a bug but I might be wrong:

```
scheme.configureEdgeSidebar((builder) => {
  builder
    .create('edgeSidebar_id', {
      anchor: 'left',
      collapsible: false,
    })
    .registerPermanentConfig('md', {
      variant: 'permanent',
      width: 256,
    })
    // .registerPersistentConfig('sm', {
    //   variant: 'temporary',
    //   width: 256,
    // })
    .registerTemporaryConfig('xs', {
      variant: 'temporary',
      width: 'auto', // 'auto' is only valid for temporary variant
    });
});
```

**Comment by siriwatknp** [comment]
@aress31 you need to register config after calling create.
`configureHeader` return HeaderBuilder instance (think of it as header controller)

`create` tell HeaderBuilder to create one instance of header (id: `header_id`), this can support multiple headers in the future

a header instance can `registerConfig` at various breakpoints.

```js
scheme.configureHeader((builder) => {
  builder.create('header_id')
    .registerConfig('xs', {
       position: 'sticky',
       initialHeight: 56,
    })
});
```
I hope this new API does not cause too much confusion.

**Comment by siriwatknp** [comment]
refer to this tutorial. https://mui-treasury.com/layout/tutorials/dashboard-layout/

**Comment by aress31** [comment]
My bad, just explored the API with Visual Studio Code - that's where TypeScript comes in handy :) - but don't you think that for common options to different breakpoints we could define them in the create function similarly to the `Edgesidebar` - that would avoid repeating the same code multiple times - ?

**Comment by siriwatknp** [comment]
I thought about while building v4 and already tried to put it in but then things get a little bit more complicated. I think it is about making better documentation because to make it available to all breakpoint, this is enough.

```js
scheme.configureHeader((builder) => {
  builder.create('header_id')
    .registerConfig('xs', {
       position: 'sticky',
       initialHeight: 56,
    })
});
```
if you define only `xs` this will apply to xs **up** (which mean all breakpoints). it follows mobile first approach.

**Comment by siriwatknp** [comment]
> But don't you think that for common behaviour common to different breakpoints we could define them in the `create function`, and if present for different breakpoints that would just override them, similarly to the `<EdgeSidebar>` - that would avoid repeating the same code multiple times - ?

One more thing, we cannot not put it in create function at the same time because you need to create an instance first and then that instance can be assign with different configuration. I think it might be better to keep only one API for now. Let see if everyone say we need it, we can improve.

**Comment by siriwatknp** [comment]
Do you mind if I close this issue?
