### ISSUE TITLE
[Request for Feature] Implementing configuration getters

### ISSUE THREAD

**Issue by aress31** [siriwatknp/mui-treasury#715]
In real world application, there might be a need of programmatically getting the current `height` of the header(s) or width of the `sidebar(s)`, therefore exposing methods to (maybe from the root context? or from the component own context)  to obtain these styling information could be a nice addition for the V4.

**EDIT**: Implementing this feature has the potential to also simplify the inner working of the `Builder.create(0`, for instance when configuring a `clipped Header`, without manually setting an `initialHeight` the `<Sidebar>` will be hidden behind the `<Header>`. However, using a getter to get the default `Material UI Appbar` default `height`, this configuration could be done under the hood, and therefore, setting `clipped` to `true` would be enough.

**Comment by siriwatknp** [comment]
@aress31 I added default initialHeight when register header config, so I think that could simplify because initialHeight is optional. However, we still need initialHeight config for server side rendering.

**Comment by aress31** [comment]
Awesome well done! 😁

**Comment by aress31** [comment]
@siriwatknp  any plans on adding the `getLayout` specification to the `doc API`? Also, I haven't played with it yet, but I assume that it is possible to get all the variables values set with using the layout `builder`, right?
