### ISSUE TITLE
MUI Treasury website doesn't correctly display demos in Firefox v75.0

### ISSUE THREAD

**Issue by derekyle** [siriwatknp/mui-treasury#721]
I get large, unformatted elements in the preview areas on the MUI Treasure website. The small preview boxes seem to work. But the clones preview page as well as the "see code" preview setup does not seem to work. Works fine in Chrome.

![image](https://user-images.githubusercontent.com/2208099/80845269-969a5d00-8bbd-11ea-8a89-06b159e43e9c.png)

![image](https://user-images.githubusercontent.com/2208099/80845280-9e5a0180-8bbd-11ea-925a-f54d6920876f.png)

**Comment by siriwatknp** [comment]
Thanks, I will take a look. In the meanwhile, please use chrome until this issue is fixed.

**Comment by pacurtin** [comment]
The preview is displayed in an iframe. For some reason for Firefox the styles are not showing in the production environment but they do show in the dev version running on local host. 

This can be seen by running `document.querySelector('iframe').contentDocument.styleSheets` in the browser console for `https://mui-treasury.com/components/content/` and `https://mui-treasury.com/components/content/`

I'm investigating why this is happening now.

**Comment by pacurtin** [comment]
It works properly when using `gatsby build` and `gatsby serve` to launch a production version of the site locally on `http://localhost:9000/components/content`

**Comment by pacurtin** [comment]
Works correctly on Edge and Safari.

**Comment by pacurtin** [comment]
In `layout/IFrame.js` we are using `react-frame-component` with `StylesProvider` from material-ui. Material-UI uses cssinjs to inject classes as they are needed. When using firefox on our live website the classes are not being injected. On my local the styles are attached to the "frame-content" div.

Local Prod Build (Firefox):
<img width="953" alt="Screen Shot 2020-05-02 at 3 04 25 PM" src="https://user-images.githubusercontent.com/17761806/80890974-a631a880-8c86-11ea-95e2-9bae2b555ab5.png">

Live Build (Firefox):
<img width="818" alt="Screen Shot 2020-05-02 at 3 04 49 PM" src="https://user-images.githubusercontent.com/17761806/80890978-b21d6a80-8c86-11ea-9154-b9c71d66b8ba.png">

Chrome acts differently. It inserts the styles into the head of the iFrame.

Live Build (Chrome):
<img width="792" alt="Screen Shot 2020-05-02 at 3 11 16 PM" src="https://user-images.githubusercontent.com/17761806/80891072-50a9cb80-8c87-11ea-80b2-d7c64cd32ef9.png">

I suspect there is an issue in the MaterialUI StylesProvider as I found the following in the code:

```
jss?: Jss;
  // TODO need info @oliviertassinari
  sheetsCache?: {};
  // TODO need info @oliviertassinari
  sheetsManager?: {};
  // TODO need info @oliviertassinari
  sheetsRegistry?: {};
```

I'll continue investigating and if appropriate I will open a ticket on Material-UI.

**Comment by pacurtin** [comment]
Having investigated further I think the problem is either in `website/src/components/layout/IFrame.js` or an environment issue. @siriwatknp I think the best thing to do is update all dependencies, delete the website cache, rebuild the project and put it live. That might be all thats needed.

**Comment by siriwatknp** [comment]
@pacurtin thanks a lot for your valuable info, I will do that tonight.

**Comment by siriwatknp** [comment]
@all-contributors please add @pacurtin as maintenance
