### ISSUE TITLE
RTL Support for layout builder

### ISSUE THREAD

**Issue by bahaa-ka** [siriwatknp/mui-treasury#771]
I used the layout builder earlier when I first started my project I didn't test it out at that time to see whether its support RTL 
in the picture below you can see the layout LTR (default case) (a dark theme with LTR)
![image](https://user-images.githubusercontent.com/36090644/81518798-857ce900-933f-11ea-9ef1-8a58ca7be731.png)
in the picture below you see the layout after changing the theme (a light theme with RTL)
![image](https://user-images.githubusercontent.com/36090644/81518862-b0ffd380-933f-11ea-8e38-79e6139c9a69.png)
the drawer goes to the right as it should be but the content and the app bar doesn't

is RTL already supported and the problem from my side? or it was never tested to see how it will behave with RTL layout?

**Comment by siriwatknp** [comment]
@bahaa-ka I don't think it supports RLT at the moment but I will look into it this week and will see how much afford for that.

**Comment by siriwatknp** [comment]
@bahaa-ka what layout version are u using?

**Comment by bahaa-ka** [comment]
"@mui-treasury/layout": "3.3.3",

**Comment by siriwatknp** [comment]
@bahaa-ka can you post your configuration here, I will use it to make documentation about upgrade layout to v4.

**Comment by bahaa-ka** [comment]
sure I can
the configuration
```
const layoutConfig = {
    "autoCollapseDisabled": false,
    "collapsedBreakpoint": "sm",
    "heightAdjustmentDisabled": false,
    "xs": {
        "sidebar": {
            "anchor": "left",
            "hidden": true,
            "inset": false,
            "variant": "temporary",
            "width": 240,
            "collapsible": false,
            "collapsedWidth": 64
        },
        "header": {
            "position": "sticky",
            "clipped": false,
            "offsetHeight": 56,
            "persistentBehavior": "fit"
        },
        "content": {
            "persistentBehavior": "fit"
        },
        "footer": {
            "persistentBehavior": "fit"
        }
    },
    "sm": {
        "sidebar": {
            "anchor": "left",
            "hidden": true,
            "inset": false,
            "variant": "persistent",
            "width": 256,
            "collapsible": false,
            "collapsedWidth": 64
        },
        "header": {
            "position": "sticky",
            "clipped": false,
            "offsetHeight": 64,
            "persistentBehavior": "fit"
        },
        "content": {
            "persistentBehavior": "fit"
        },
        "footer": {
            "persistentBehavior": "fit"
        }
    },
    "md": {
        "sidebar": {
            "anchor": "left",
            "hidden": true,
            "inset": false,
            "variant": "permanent",
            "width": 256,
            "collapsible": true,
            "collapsedWidth": 64
        },
        "header": {
            "position": "sticky",
            "clipped": false,
            "offsetHeight": 64,
            "persistentBehavior": "fit"
        },
        "content": {
            "persistentBehavior": "fit"
        },
        "footer": {
            "persistentBehavior": "fit"
        }
    }
};
```
code where the layout components used:
```
<ThemeProvider theme={theme}>
            <CssBaseline/>
            <Root omitThemeProvider={true} config={authenticated ? authLayoutConfig : unauthLayoutConfig}>
                {({headerStyles, sidebarStyles, opened}) => (
                    <>
                        <Header>
                            <ApplicationBar
                                opened={opened}
                                headerStyles={headerStyles.leftTrigger}
                            />
                        </Header>
                        {authenticated ? <Sidebar>
                            <div className={sidebarStyles.container}>
                                <DrawerMenu/>
                            </div>
                        </Sidebar> : null}
                        <Content>
                            <div>
                                <Switch>
                                    <Route path={match.path + AdminRoutes.LOGIN} exact component={LoginView}/>
                                   // other routes 
                                </Switch>
                            </div>
                        </Content>
                    </>
                )}
            </Root>
        </ThemeProvider>
```

**Comment by siriwatknp** [comment]
@bahaa-ka Can you provide the code or sandbox demo that shows how you make RTL?

**Comment by siriwatknp** [comment]
Please run `yarn upgrade @mui-treasury/layout@^` and select `v4.4.0`. Everything should work automatically if you are already set up material-ui RTL in theme.

Demo here: https://mui-treasury.com/layout/examples/rtl-support

**Comment by bahaa-ka** [comment]
@siriwatknp  thank you for implementing this feature
I think in the latest version there were breaking changes. Root component props are completely different and I also notice that there is a dependency on styled-components in order to get Header, Sidebar, Content, Footer components (where it didn't exist in 3.3.3) 
the way I import the layout components before 
import {
    Root,
    Header,
    Sidebar,
    Content,
} from "@mui-treasury/layout";
 but after the update, only Root component is exported as that level and instead, I have to import the component getters to get the other three 
is there something I have to change here? (definitely yes) but can you point me where to make the changes?
where to assign the config for example

**Comment by bahaa-ka** [comment]
never mind I just took a look and found the new API you created in the latest version and I am currently migrating to use instead of the current
@siriwatknp keep up the good work :)
