### ISSUE TITLE
cannot install dependencies because of fontawesome 401

### ISSUE THREAD

**Issue by alexichepura** [siriwatknp/mui-treasury#775]
Hello,
simple git clone -> yarn install gives this error

<img width="661" alt="fontawesome 401 Unauthorized" src="https://user-images.githubusercontent.com/5582266/81712850-c844db00-947d-11ea-8780-2e89e08d2a0c.png">

or is there any workaround?

**Comment by murbanowicz** [comment]
I have exactly same issue! Was trying to prepare some PR but cannot install...

**Comment by siriwatknp** [comment]
Will fix that asap, sorry for this issue.

**Comment by siriwatknp** [comment]
@alexichepura @murbanowicz can you try again. pull latest `master`, delete yarn.lock (if exists) and run `yarn install`
