### ISSUE TITLE
RTL Layout

### ISSUE THREAD

**Issue by sstubbs** [siriwatknp/mui-treasury#779]
Hi,

I intend to use this great project for a dashboard and the presets look great at https://codesandbox.io/s/material-ui-layout-7mn9xq3nnj. How would you suggest I add right to left support?

**Comment by sstubbs** [comment]
I see there is already an issue about this https://github.com/siriwatknp/mui-treasury/issues/771

**Comment by siriwatknp** [comment]
Duplicate with #771
