### ISSUE TITLE
[Doc] Dynamically fetch Header height and SideBar width

### ISSUE THREAD

**Issue by aress31** [siriwatknp/mui-treasury#782]
I am trying to create a loading screen that would only cover the `Content` area of the layout. In order to style the `CSS` of my `Loader`, I need to be able to dynamically fetch the following information from the `Layout builder`:

- Header height
- Sidebar width
- Sidebar status - is the sidebar open or closed

The following code snippet shows my CSS styling - including the comments  so that you can better understand what I am aiming to achieve:
```js
const useStyles = makeStyles((theme) => ({
  // TODO: Track https://github.com/siriwatknp/mui-treasury/issues/715
  root: {
    alignItems: 'center',
    display: 'flex',
    flexDirection: 'column',
    height: (props) =>
      // 64px is the Header height
      // ideally we would want to fetch this value from the Layout builder
      props.initialLoad ? '100vh' : 'calc(100vh - 64px)',
    justifyContent: 'center',
    width: (props) =>
      // 256px is the Sidebar width
      // ideally we would want to fetch this value from the Layout builder
      // add an if open case to properly handle persistent Sidebar
      props.initialLoad ? '100vw' : 'calc(100vw - 256px)',
    [theme.breakpoints.down('sm')]: {
      width: '100vw',
    },
  },
}));
``` 

I am wondering whether, you could provide a working example of how you would approach this problem to achieve the desired responsive behaviour. Also could kindly document that on the website as it could help many other people.

**Comment by aress31** [comment]
I managed to get somewhere with the following code:
```js
const useStyles = makeStyles((theme) => ({
  root: {
    alignItems: 'center',
    backgroundColor: 'red',
    display: 'flex',
    flexDirection: 'column',
    height: (props) =>
      props.initialLoad
        ? '100vh'
        : `calc(100vh - ${props.headerConfig.md.initialHeight}px)`,
    justifyContent: 'center',
    width: (props) =>
      props.initialLoad
        ? '100vw'
        : `calc(100vw - ${props.edgeSidebarConfig.configMapById.edgeSidebar_id.md.width}px)`,
    [theme.breakpoints.down('sm')]: {
      backgroundColor: 'blue',
      height: (props) =>
        props.initialLoad
          ? '100vh'
          : `calc(100vh - ${props.headerConfig.sm.initialHeight}px)`,
      width: (props) =>
        props.initialLoad || !props.edgeSidebarState
          ? '100vw'
          : `calc(100vw - ${props.edgeSidebarConfig.configMapById.edgeSidebar_id.sm.width}px)`,
    },
    [theme.breakpoints.down('xs')]: {
      backgroundColor: 'green',
      height: (props) =>
        props.initialLoad
          ? '100vh'
          : `calc(100vh - ${props.headerConfig.xs.initialHeight}px)`,
      width: '100vw',
    },
  },
}));
```

Everything seems to be working fine, with the exception of the `temporary Sidebar`  - for the xs breakpoint.

My `Loader` component is instructed to fill the entire viewport - `100vw` and `100vh` and this instruction is respected as long as the `Sidebar` is closed. As soon as I open the `temporary Sidebar`, the Loader component supposed to fill the entire viewport get squashed -  see the following screenshot, the green background is supposed to fill up the entire width.

![image](https://user-images.githubusercontent.com/11601622/81815423-de0bdc00-9521-11ea-9bcb-4f1d588a66df.png)

![image](https://user-images.githubusercontent.com/11601622/81815732-435fcd00-9522-11ea-866e-4af5d12ba51a.png)

**Comment by siriwatknp** [comment]
I suggest another alternative. Can you add `position: relative` css to Content and then for Loading use `position: absolute` with `top:0, left: 0, bottom: 0, right: 0`

```jsx
<Content> // position: relative
  <Overlay> // position: absolute, top: 0, left: 0, bottom: 0, right: 0
    <Loader />
  </Overlay>
</Content>
```
