### ISSUE TITLE
[Request For Feature] Multiple Headers using ID

### ISSUE THREAD

**Issue by aress31** [siriwatknp/mui-treasury#791]
Could it be possible to implement support for multiple `Headers` using a unique `id`. This could be achieved in a similar fashion than the `EdgeSidebar`?

Could be something like:
```js
scheme.configureHeader((builder) => {
    builder
      .create('marketting_header')
      .registerConfig('sm', {
        clipped: true,
        initialHeight: 32,
      })
      .registerConfig('xs', {
        clipped: false,
        initialHeight: 24,
        position: 'static',
      });
  });
  
  scheme.configureHeader((builder) => {
    builder
      .create('navigation_header')
      .registerConfig('sm', {
        clipped: true,
        initialHeight: 64,
      })
      .registerConfig('xs', {
        clipped: false,
        initialHeight: 56,
        position: 'sticky',
      });
  });

<Header color='primary' headerId='marketting_header'>
    <ContentHeader/>
</Header>
<Header
    color='default'
    elevation={scrollTrigger ? 4 : 0}
    headerId='navigation_header'
>
    <ContentHeader1/>
</Header>
```

Also whilst we are talking about possible improvements for the `Header` component, is it normal to display the `SidebarTrigger` even when the configuration does not include support for a `Sidebar` for given breakpoints?

Would it not be better and more optimised to simply not instantiate and display the object at all for such use cases?

**EDIT:** Also, to fully be responsive, an option to hide the `Header` for given breakpoints would be welcome.

**Comment by siriwatknp** [comment]
Can you provide the design?

**Comment by aress31** [comment]
@siriwatknp not sure what you mean by design but I think that your approach to multiple `SideBar` is very good - I personally like it a lot! So as mentioned the same design could be used, the `Headers` already have a `unique ID`, these `IDs` could be used to instantiate and easily configure as many `Headers` as we need.

For example, as shown in my previous post, a `Header` could be on the very top used for marketing purposes, e.g. contact information and social medias whilst another could be used for various application controls, e.g. languages and dark mode switch and a last one could be used for navigation purposes. All stacked one of top of another, that is why I think that supporting multiple `Headers` is a must do and as I said the `unique IDs` approach would do the job.

**Comment by siriwatknp** [comment]
Is it something like this?
![image](https://user-images.githubusercontent.com/18292247/81922849-eb4ec680-9606-11ea-9d82-e04397dd3658.png)

**Comment by siriwatknp** [comment]
I am also thinking about another feature where Header is auto hidden when scroll down like https://material.io/design

**Comment by aress31** [comment]
Yes that's exactly something like this! And for the hide on scroll and elevate on scroll, material UI support these behaviours so there is no need to implement from scratch.
