### ISSUE TITLE
How i get the source code about peapod components?

### ISSUE THREAD

**Issue by moonketo** [siriwatknp/mui-treasury#830]
it's for commercial? 
i will use as just reference.
I remember it used to be open source at past time.
thanks for reading.

**Comment by siriwatknp** [comment]
@mikestaub your call.

**Comment by mikestaub** [comment]
@moonketo The library is open sourced under MIT license here, you can use it for commercial. https://github.com/mikestaub/mui-treasury-deprecate

Disclaimer: the lib is experimental as we are heavily modifying the components.

Please consider submitting PRs back into that repo if you make any fixes or improvements. :)
