### ISSUE TITLE
`useFourThreeCardMediaStyles` Not Found

### ISSUE THREAD

**Issue by buddies2705** [siriwatknp/mui-treasury#849]
Hey, 

Thanks for building these beautiful components. I am trying [this demo](https://mui-treasury.com/components/card).

But `useFourThreeCardMediaStyles` is missing from `@mui-treasury/styles/cardMedia` in library

**Comment by siriwatknp** [comment]
@buddies2705 can you provide the version in package.json
"@mui-treasury/styles: ??"

**Comment by siriwatknp** [comment]
should be fixed in `@mui-treasury/styles: 1.7.1`.
Try `yarn upgrade @mui-treasury/styles@^` and choose `1.7.1`.

**Comment by buddies2705** [comment]
"@mui-treasury/components": "^1.4.0",
    "@mui-treasury/styles": "^0.3.2",

**Comment by buddies2705** [comment]
I am using NPM and I ran  `npm update @mui-treasury/styles`

now the version is - `^0.3.6`

How to upgrade to `1.7.1`

**Comment by siriwatknp** [comment]
tested in codesandbox, it works. so I will close this issue.
