### ISSUE TITLE
new feature: ability to disable sidebar auto expand at mouse over

### ISSUE THREAD

**Issue by fgiust** [siriwatknp/mui-treasury#854]
if I didn't overlooked the documentation there is no way at this moment to disable the auto-expansion of sidebar at rollover when the sidebar is manually closed.
I would like to be able to disable this behaviour in order to keep the state selected by the user (actually showing tooltip for the selected item instead of expanding the whole sidebar).

I see the expand on mousever behaviour is hardcoded in SidebarContext.js and it's actually implemented using an inline style, which prevent for any kind of style overlay. 
It would be great to have it configurable on scheme (e.g. scheme.setAutoExpandOnMouseover(false))

**Comment by siriwatknp** [comment]
I see. This should be a quick fix, I'll take a look today.

**Comment by siriwatknp** [comment]
By the way, what is your experience using this library. Is the configuration part make sense to you. Is there any thing should be improved?

**Comment by maurosbu** [comment]
@siriwatknp many thanks for the library, it is awesome! 
I'm upgrading from v3 to v4 and as @fgiust said, there is no way to disable the auto-expansion of sidebar at rollover when the sidebar is manually closed. 
I need this feature in order to get the same behaviour as the implementation with v3.

**Comment by siriwatknp** [comment]
@fgiust @maurosbu `autoExpanded` is added.

run `yarn upgrade @mui-treasury/layout@^` and select `4.3.0`. This config is set to `false` by default so after you upgrade, it should work instantly.

by the way, full documentation is here. https://mui-treasury.com/layout/features/auto-expanded

**Comment by maurosbu** [comment]
@siriwatknp It works, many thanks!!!
