### ISSUE TITLE
Dark CollapseBtn inside Mui ThemeProvider

### ISSUE THREAD

**Issue by maurosbu** [siriwatknp/mui-treasury#863]
@siriwatknp first I'd like to thank you for such a great library!
I force the sidebar to use dark them through the use of ThemeProvider of Material UI, but collapss button (CollapseBtn is not styled correctly). Is this a bug? Am I doing it wrong?

Many thanks in advance for your help.
Mauro

    import styled from 'styled-components';
    import Layout, {
      Root,
      getHeader,
      getDrawerSidebar,
      getSidebarTrigger,
      getSidebarContent,
      getCollapseBtn,
      getContent,
    } from "@mui-treasury/layout";
    import { ThemeProvider } from '@material-ui/core';
    // other imports   

    const Header = getHeader(styled);
    const DrawerSidebar = getDrawerSidebar(styled);
    const SidebarTrigger = getSidebarTrigger(styled);
    const SidebarContent = getSidebarContent(styled);
    const CollapseBtn = getCollapseBtn(styled);
    const Content = getContent(styled);

    const scheme = Layout();
    // layout configuration

    // App component
    class App extends React.Component {
	  componentDidMount() {
	      // code
	  }

	  render() {
             const selectedTheme = this.props.selectedTheme;
             const themes = { light: MyLightTheme, dark: MyDarkTheme };
             const theme = themes[selectedTheme];
             const styles = this.props.classes;

	    return (
	      <Root theme={theme} scheme={scheme}>
	        {
	          ({ state: { sidebar } }) => {
	            return (
	              <>
	                <Router history={history}>
	                  <ScrollToTop />
	                  <CssBaseline />
	                  ...
	                  <ThemeProvider theme={MyDarkTheme}>
	                    <DrawerSidebar sidebarId="left_sidebar">
	                      <SidebarContent>
	                        <AppSidebar collapsed={sidebar.left_sidebar.collapsed} />
	                      </SidebarContent>
	                      <CollapseBtn />
	                    </DrawerSidebar>
	                  </ThemeProvider>
	                  ...
	                </Router>
	              </>
	            );
	          }
	        }
	      </Root>
	    );
	  }
    }

**Comment by siriwatknp** [comment]
Can you capture your screen and post it here?

**Comment by maurosbu** [comment]
@siriwatknp here you are!

<img width="1069" alt="MuiTreasuryLayoutV4" src="https://user-images.githubusercontent.com/1393996/84529332-92478080-ace1-11ea-9936-50d81d0b4e03.png">

**Comment by maurosbu** [comment]
@siriwatknp this is what I see on mouse hover.

<img width="255" alt="MuiTreasuryLayoutV4MouseHover" src="https://user-images.githubusercontent.com/1393996/84562750-315a8f80-ad57-11ea-9b92-062d27b5dec4.png">

**Comment by maurosbu** [comment]
@siriwatknp in the following two screenshots V3 of Muy Treasury Layout

Normal
<img width="256" alt="MuiTreasuryLayoutV3" src="https://user-images.githubusercontent.com/1393996/84563510-5d2c4400-ad5c-11ea-81e0-bcecd0ef1b4f.png">

Mouse Hover
<img width="259" alt="MuiTreasuryLayoutV3MouseHover" src="https://user-images.githubusercontent.com/1393996/84563516-65847f00-ad5c-11ea-944c-5db70c979ec8.png">

**Comment by siriwatknp** [comment]
please run `yarn upgrade @mui-treasury/layout@^` and select `v4.4.1`. It should work instantly.
Demo here : https://mui-treasury.com/layout/examples/dark-theme/
