### ISSUE TITLE
[Layout] TypeError: Cannot read property 'slice' of undefined

### ISSUE THREAD

**Issue by raghav0622** [siriwatknp/mui-treasury#926]
When setting up layout in scheme.configure**(...) above mentione error is shown
code: -

![Screenshot 2020-08-09 202721](https://user-images.githubusercontent.com/29769428/89735275-f63abb00-da7e-11ea-83dc-8195e109c85c.png)
![Screenshot 2020-08-09 202802](https://user-images.githubusercontent.com/29769428/89735276-f8047e80-da7e-11ea-8af7-83acc8ce55d9.png)
![Screenshot 2020-08-09 202844](https://user-images.githubusercontent.com/29769428/89735277-f8047e80-da7e-11ea-886c-5f7451feec2d.png)

**Comment by siriwatknp** [comment]
Did you follow this tutorial? https://mui-treasury.com/layout/tutorials/dashboard-layout/

If you can provide codesandbox or github repo that I can reproduce, I can help.

Finally, I haven't test with `styled` from `@material-ui/styles` before. will try this weekend.

**Comment by raghav0622** [comment]
> Did you follow this tutorial? https://mui-treasury.com/layout/tutorials/dashboard-layout/
> 
> If you can provide codesandbox or github repo that I can reproduce, I can help.
> 
> Finally, I haven't test with `styled` from `@material-ui/styles` before. will try this weekend.

Yes i did follow the tutorial, all i am using is Nextjs and rest of the code is here!

**Comment by raghav0622** [comment]
> Did you follow this tutorial? https://mui-treasury.com/layout/tutorials/dashboard-layout/
> 
> If you can provide codesandbox or github repo that I can reproduce, I can help.
> 
> Finally, I haven't test with `styled` from `@material-ui/styles` before. will try this weekend.

@siriwatknp 
please make this library compatible with default exported styled from @material-ui/core as styled-components RFC is a long time wait before it is finally adopted (heated debate is going on perf vs dev-exp etc in RFC in @material-ui/core), till then make it compatible with styled as i wouldn't want to increase complexity of project by using tailwindcss, material-ui and styled-components all together with nextjs. (opens room for more bugs and typerrors).
Thanks for this awesome project though

**Comment by neyasov** [comment]
@siriwatknp Bug related to alpha versions of material-ui v5.0.0-alpha.6
export "keys" renamed to "breakpointKeys"
https://github.com/mui-org/material-ui/pull/21759

**Comment by siriwatknp** [comment]
@raghav0622 @neyasov Should I make a release as @mui-treasury/layout v5.0.0 for this fix? What do you guys think?

**Comment by neyasov** [comment]
@siriwatknp I think we need alpha or beta release, because there may still be breaking changes to @material-ui v5

**Comment by raghav0622** [comment]
> @raghav0622 @neyasov Should I make a release as @mui-treasury/layout v5.0.0 for this fix to follow material-ui/core version? What do you guys think?

thats the best way, this way this repo will match to version of material-ui and also consider using default styled exported from @material-ui/core as whaterver styled-components library material-ui adopts, it will export it styled from its core...

**Comment by agemxc** [comment]
With lerna publish you can make an alpha version,like v5.0.0-alpha.01,
when we have assurance that material ui is stable and react 17 its bug free you can create the 5.0.0 Version
What you think?
For those who trying to use the version  v5.0.0 of material-ui only works 
"@material-ui/core": "5.0.0-alpha.2" after this version they made a renaming .

**Comment by siriwatknp** [comment]
Layout v5 has been released! https://www.npmjs.com/package/@mui-treasury/layout/v/5.0.0
