### ISSUE TITLE
Sidebar Drawer

### ISSUE THREAD

**Issue by danschoe** [siriwatknp/mui-treasury#933]
How can I have BOTH a left and right sidebar/drawer ? With hamburger on left end AND right end in top nav bar which reduces each sidebar to mini-sidebar independently?

**Comment by siriwatknp** [comment]
Multiple sidebars is definitely possible. Please take a look at these docs, feel free to continue in this issue in case you have more questions.
https://mui-treasury.com/layout/examples/secondary-sidebar
